adminUser:
  password: vault:chatterflint/adminUser:password
  username: admin
dashboardUrl: https://dashboard.play-jxaas.live
enableDocker: false
pipelineUser:
  email: arcalos-admin@googlegroups.com
  token: vault:chatterflint/pipelineUser:token
  username: cb-cloud-native-ci-cd-play[bot]
prow:
  hmacToken: vault:chatterflint/prow:hmacToken
segmentWriteKey: vault:chatterflint:segmentWriteKey
